package paodamanha;

import javax.imageio.ImageIO;
import java.net.URL;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;

public class JframePadariaMain extends javax.swing.JFrame {

    /**
     * Creates new form JframePadariaMain
     */
    public JframePadariaMain() {
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon backgroundImage = null;
        String imagePath = "Images/Banner.jfif";
        
        try {
            URL imageURL = getClass().getClassLoader().getResource(imagePath);
            if (imageURL != null) {
                backgroundImage = new ImageIcon(ImageIO.read(imageURL));
            }else{
                System.out.println("Erro: não consegui encontrar a imagen");
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Erro de E/S ao carregar");
        }
        
        JLabel backgroundLabel = new JLabel(backgroundImage);
        
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        JLayeredPane layeredPane = getRootPane().getLayeredPane();
        
        layeredPane.add(backgroundLabel, JLayeredPane.FRAME_CONTENT_LAYER);
        backgroundLabel.setLocation(0, 0);
        
        JPanel contentPanel = (JPanel) getContentPane();
        contentPanel.setOpaque(false);
        
        addComponentListener(new java.awt.event.ComponentAdapter(){
            public void componentResized(java.awt.event.ComponentEvent evt) {
                backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
                layeredPane.revalidate();
                layeredPane.repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePadariaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePadariaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePadariaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePadariaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePadariaMain().setVisible(true);
            }
        });
        
        SwingUtilities.invokeLater(() -> {new JframePadariaMain().setVisible(true);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
